
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	private global::Gtk.Label label1;
	private global::Gtk.Entry entry1;
	private global::Gtk.Label label2;
	private global::Gtk.Entry entry2;
	private global::Gtk.Label label3;
	private global::Gtk.RadioButton radb1;
	private global::Gtk.RadioButton radiobutton2;
	private global::Gtk.RadioButton radiobutton3;
	private global::Gtk.Label label4;
	private global::Gtk.CheckButton chPortu;
	private global::Gtk.CheckButton chChile;
	private global::Gtk.CheckButton chReino;
	private global::Gtk.CheckButton chMace;
	private global::Gtk.CheckButton chAustra;
	private global::Gtk.Label label5;
	private global::Gtk.SpinButton spinb1;
	private global::Gtk.Label label6;
	private global::Gtk.Calendar calendar1;
	private global::Gtk.Button button1;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Codigo: ");
		this.fixed1.Add (this.label1);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label1]));
		w1.X = 125;
		w1.Y = 24;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.entry1 = new global::Gtk.Entry ();
		this.entry1.CanFocus = true;
		this.entry1.Name = "entry1";
		this.entry1.IsEditable = true;
		this.entry1.InvisibleChar = '●';
		this.fixed1.Add (this.entry1);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entry1]));
		w2.X = 199;
		w2.Y = 17;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Nombre: ");
		this.fixed1.Add (this.label2);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label2]));
		w3.X = 122;
		w3.Y = 63;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.entry2 = new global::Gtk.Entry ();
		this.entry2.CanFocus = true;
		this.entry2.Name = "entry2";
		this.entry2.IsEditable = true;
		this.entry2.InvisibleChar = '●';
		this.fixed1.Add (this.entry2);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entry2]));
		w4.X = 201;
		w4.Y = 58;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("1. Capital de México");
		this.fixed1.Add (this.label3);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label3]));
		w5.X = 21;
		w5.Y = 109;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.radb1 = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("DF"));
		this.radb1.CanFocus = true;
		this.radb1.Name = "radb1";
		this.radb1.DrawIndicator = true;
		this.radb1.UseUnderline = true;
		this.radb1.Group = new global::GLib.SList (global::System.IntPtr.Zero);
		this.fixed1.Add (this.radb1);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.radb1]));
		w6.X = 20;
		w6.Y = 131;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.radiobutton2 = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Guadalajara"));
		this.radiobutton2.CanFocus = true;
		this.radiobutton2.Name = "radiobutton2";
		this.radiobutton2.DrawIndicator = true;
		this.radiobutton2.UseUnderline = true;
		this.radiobutton2.Group = this.radb1.Group;
		this.fixed1.Add (this.radiobutton2);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.radiobutton2]));
		w7.X = 83;
		w7.Y = 131;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.radiobutton3 = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Monterrey"));
		this.radiobutton3.CanFocus = true;
		this.radiobutton3.Name = "radiobutton3";
		this.radiobutton3.DrawIndicator = true;
		this.radiobutton3.UseUnderline = true;
		this.radiobutton3.Group = this.radb1.Group;
		this.fixed1.Add (this.radiobutton3);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.radiobutton3]));
		w8.X = 203;
		w8.Y = 132;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("2. Paises de Europa");
		this.fixed1.Add (this.label4);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label4]));
		w9.X = 21;
		w9.Y = 201;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.chPortu = new global::Gtk.CheckButton ();
		this.chPortu.CanFocus = true;
		this.chPortu.Name = "chPortu";
		this.chPortu.Label = global::Mono.Unix.Catalog.GetString ("Portugal");
		this.chPortu.DrawIndicator = true;
		this.chPortu.UseUnderline = true;
		this.fixed1.Add (this.chPortu);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.chPortu]));
		w10.X = 25;
		w10.Y = 228;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.chChile = new global::Gtk.CheckButton ();
		this.chChile.CanFocus = true;
		this.chChile.Name = "chChile";
		this.chChile.Label = global::Mono.Unix.Catalog.GetString ("Chile");
		this.chChile.DrawIndicator = true;
		this.chChile.UseUnderline = true;
		this.fixed1.Add (this.chChile);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.chChile]));
		w11.X = 25;
		w11.Y = 254;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.chReino = new global::Gtk.CheckButton ();
		this.chReino.CanFocus = true;
		this.chReino.Name = "chReino";
		this.chReino.Label = global::Mono.Unix.Catalog.GetString ("Reino Unido");
		this.chReino.DrawIndicator = true;
		this.chReino.UseUnderline = true;
		this.fixed1.Add (this.chReino);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.chReino]));
		w12.X = 25;
		w12.Y = 282;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.chMace = new global::Gtk.CheckButton ();
		this.chMace.CanFocus = true;
		this.chMace.Name = "chMace";
		this.chMace.Label = global::Mono.Unix.Catalog.GetString ("Macedonia");
		this.chMace.Active = true;
		this.chMace.DrawIndicator = true;
		this.chMace.UseUnderline = true;
		this.fixed1.Add (this.chMace);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.chMace]));
		w13.X = 26;
		w13.Y = 311;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.chAustra = new global::Gtk.CheckButton ();
		this.chAustra.CanFocus = true;
		this.chAustra.Name = "chAustra";
		this.chAustra.Label = global::Mono.Unix.Catalog.GetString ("Australia");
		this.chAustra.DrawIndicator = true;
		this.chAustra.UseUnderline = true;
		this.fixed1.Add (this.chAustra);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.chAustra]));
		w14.X = 27;
		w14.Y = 340;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("3. Cantidad de estados de los que se compone México");
		this.fixed1.Add (this.label5);
		global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label5]));
		w15.X = 22;
		w15.Y = 383;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.spinb1 = new global::Gtk.SpinButton (0, 100, 1);
		this.spinb1.CanFocus = true;
		this.spinb1.Name = "spinb1";
		this.spinb1.Adjustment.PageIncrement = 10;
		this.spinb1.ClimbRate = 1;
		this.spinb1.Numeric = true;
		this.fixed1.Add (this.spinb1);
		global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.spinb1]));
		w16.X = 30;
		w16.Y = 405;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label6 = new global::Gtk.Label ();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("4. Dia en que terminó la segunda guerra mundial");
		this.fixed1.Add (this.label6);
		global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label6]));
		w17.X = 23;
		w17.Y = 455;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.calendar1 = new global::Gtk.Calendar ();
		this.calendar1.CanFocus = true;
		this.calendar1.Name = "calendar1";
		this.calendar1.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(35));
		this.fixed1.Add (this.calendar1);
		global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.calendar1]));
		w18.X = 41;
		w18.Y = 484;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button1 = new global::Gtk.Button ();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString ("Terminar");
		this.fixed1.Add (this.button1);
		global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.button1]));
		w19.X = 415;
		w19.Y = 598;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 560;
		this.DefaultHeight = 683;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.button1.Clicked += new global::System.EventHandler (this.OnButton1Clicked);
	}
}
